### ISSUE TITLE
No symbolic icons

### ISSUE THREAD

**Issue by ghost** [varlesh/papirus-colors#2]
The icon theme doesn't use symbolic icons, for the connect and disconnect icons in the networks applet for example. The standard papirus theme, from which it should inherit these symbols does have and use them if applied. Can you please fix this? Thanks

**Comment by varlesh** [comment]
You can show screenshot? What DE you use?

**Comment by varlesh** [comment]
This version contained only folders with full support KDE Color Scheme.
About tray.... For KDE used icons from plasma theme, if you mean plasma-nm
![image](https://user-images.githubusercontent.com/8083855/170250961-a9b8d3a8-1e21-442a-aff5-d0244f2f14e8.png)

**Comment by varlesh** [comment]
with Breeze plasma theme:
![image](https://user-images.githubusercontent.com/8083855/170251192-2d8a1713-10b8-4920-83be-e0061779c424.png)

**Comment by ghost** [comment]
I'm talking about these icons in plasma-nm:

![Papirus Color](https://user-images.githubusercontent.com/20848852/170255917-87fddbe7-f58c-4563-9efa-ffe2555a25fe.png)
![Papirus](https://user-images.githubusercontent.com/20848852/170255924-dd76c1d4-3420-4543-8c89-7c9a26aa09f7.png)

I think so far I have only noticed it here and in notifications like here:

![Papirus color notification](https://user-images.githubusercontent.com/20848852/170257230-93822535-11d1-432c-98ce-9a78998aaf96.png)

![Papirus notification](https://user-images.githubusercontent.com/20848852/170257569-f4a661a5-42ed-4ba1-9925-6d95f8d59d2b.png)

**Comment by varlesh** [comment]
This icon theme contained ONLY folders.

**Comment by varlesh** [comment]
Why places icons applied for status? Report this to KDE devs!

**Comment by varlesh** [comment]
Read this tread, i think you understand about KDE:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3061

**Comment by varlesh** [comment]
It's solved if remove `network` symlinks?

**Comment by varlesh** [comment]
About `network` symlink... This symlink added for PCManFm-Qt:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/a7f0c46e148d24760308806c84bc144c9f60079e

**Comment by varlesh** [comment]
I'm remove `network` symlinks. Try it from git

**Comment by ghost** [comment]
Thank you, that works!
